# Seed content mirrored from frontend/src/lib/data.js
# Used on first startup to populate empty projects/articles/roles collections.

PROJECTS_SEED = [
    {
        "slug": "vault-fintech",
        "title": "Vault — Private Banking, Reimagined",
        "client": "Vault Holdings",
        "domain": "Fintech",
        "year": "2025",
        "summary": "A zero-trust private banking platform serving 180k high-net-worth clients across 22 countries.",
        "metrics": [
            {"k": "94ms", "v": "p95 latency"},
            {"k": "+38%", "v": "AUM growth"},
            {"k": "SOC 2 II", "v": "Certified"},
        ],
        "cover": "https://images.unsplash.com/photo-1723785735443-16ffd373f398?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA0MTJ8MHwxfHNlYXJjaHwzfHxmaW50ZWNoJTIwZGFzaGJvYXJkJTIwYXBwJTIwaW50ZXJmYWNlJTIwbW9kZXJufGVufDB8fHx8MTc3NzI5MjA0OHww&ixlib=rb-4.1.0&q=85",
        "video": "https://cdn.pixabay.com/video/2024/04/20/209336-939489619_large.mp4",
        "services": ["Web", "Mobile", "AI"],
    },
    {
        "slug": "helix-health",
        "title": "Helix — Clinician-Grade Care OS",
        "client": "Helix Health",
        "domain": "Healthcare",
        "year": "2025",
        "summary": "HIPAA-grade clinical workspace powering 4.2M patient encounters annually across 12 hospital networks.",
        "metrics": [
            {"k": "−42%", "v": "Charting time"},
            {"k": "99.99%", "v": "Uptime"},
            {"k": "HL7 FHIR", "v": "Compliant"},
        ],
        "cover": "https://images.unsplash.com/photo-1633098096956-afdc8bcc8552?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDV8MHwxfHNlYXJjaHwyfHxoZWFsdGhjYXJlJTIwdGVjaG5vbG9neSUyMGFic3RyYWN0JTIwc2NyZWVufGVufDB8fHx8MTc3NzI5MjA0N3ww&ixlib=rb-4.1.0&q=85",
        "video": "https://cdn.pixabay.com/video/2023/10/11/184416-874659133_large.mp4",
        "services": ["Mobile", "AI", "Data"],
    },
    {
        "slug": "atlas-analytics",
        "title": "Atlas — Institutional Analytics",
        "client": "Atlas Capital",
        "domain": "Data",
        "year": "2024",
        "summary": "Predictive market intelligence used by 340 hedge funds to price risk across equities, FX, and credit.",
        "metrics": [
            {"k": "12B", "v": "Rows/day"},
            {"k": "8ms", "v": "Query p50"},
            {"k": "23 sources", "v": "Real-time feeds"},
        ],
        "cover": "https://images.pexels.com/photos/32299899/pexels-photo-32299899.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "video": "https://cdn.pixabay.com/video/2024/11/09/240120_large.mp4",
        "services": ["Web", "Data", "AI"],
    },
    {
        "slug": "noor-commerce",
        "title": "Noor — Luxury Commerce",
        "client": "Noor Atelier",
        "domain": "Retail",
        "year": "2024",
        "summary": "Headless commerce flagship for a luxury fashion house — shipping in 38 countries with white-glove logistics.",
        "metrics": [
            {"k": "+61%", "v": "Conversion"},
            {"k": "1.1s", "v": "LCP"},
            {"k": "38", "v": "Markets"},
        ],
        "cover": "https://images.unsplash.com/photo-1483985988355-763728e1935b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "video": "https://cdn.pixabay.com/video/2020/07/30/45942-447087782_large.mp4",
        "services": ["Web", "Brand"],
    },
    {
        "slug": "mira-voice",
        "title": "Mira — AI Voice Agent",
        "client": "Mira Labs",
        "domain": "AI",
        "year": "2025",
        "summary": "Real-time voice AI handling 2.4M customer calls/month across 9 languages with sub-400ms end-to-end latency.",
        "metrics": [
            {"k": "380ms", "v": "End-to-end"},
            {"k": "9", "v": "Languages"},
            {"k": "96%", "v": "CSAT"},
        ],
        "cover": "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "video": "https://cdn.pixabay.com/video/2024/03/18/204306-925350094_large.mp4",
        "services": ["AI"],
    },
    {
        "slug": "orbital-retail",
        "title": "Orbital — AI Merchandising",
        "client": "Orbital Retail",
        "domain": "Retail",
        "year": "2024",
        "summary": "AI-driven merchandising engine that reprices 1.4M SKUs nightly across 900 retail stores.",
        "metrics": [
            {"k": "+19%", "v": "Gross margin"},
            {"k": "1.4M", "v": "SKUs"},
            {"k": "900", "v": "Stores"},
        ],
        "cover": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "video": "https://cdn.pixabay.com/video/2019/11/03/28586-371443433_large.mp4",
        "services": ["AI", "Data"],
    },
]


ARTICLES_SEED = [
    {
        "slug": "ai-as-infrastructure",
        "title": "AI as Infrastructure — Why your org chart is wrong",
        "excerpt": "Most companies treat AI as a feature. The ones pulling ahead treat it as infrastructure. Here's what that actually means in practice.",
        "category": "AI",
        "date": "Dec 10, 2025",
        "read_time": "9 min",
        "author": "Elena Moreau",
        "cover": "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": True,
        "body": [
            "We've spent the last three years embedded inside product teams shipping LLMs to millions of users. The companies quietly winning share the same posture: AI is not a feature shipped into a product. It's a substrate the product runs on — like a database, like a CDN.",
            "That reframing is load-bearing. If AI is infrastructure, then evals are tests, prompts are contracts, and the operations team owns the uptime of intelligence itself. We'll walk through the exact team topology and the tooling we'd install on day zero.",
            "From there, the playbook is mostly about discipline — guardrails, observability, and the humility to roll back a model the same way you'd roll back a migration.",
        ],
    },
    {
        "slug": "performance-budgets-2026",
        "title": "Performance Budgets for the AI-Native Web",
        "excerpt": "A modern web stack now carries 4–6 model calls on a single page load. Your Core Web Vitals haven't changed. Your budget has.",
        "category": "Web",
        "date": "Nov 24, 2025",
        "read_time": "7 min",
        "author": "Kenji Park",
        "cover": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": False,
        "body": [
            "LCP, INP, and CLS still define the ceiling of what the web can feel like. But the floor just moved: we're routinely seeing pages ship 4–6 streamed model calls on first paint, and the browser isn't getting faster.",
            "We'll share the exact perf budgets we ship to clients — broken down by route type, and by the nature of the model calls on the page.",
        ],
    },
    {
        "slug": "native-or-react-native",
        "title": "Native, React Native, or Flutter — The 2026 Decision Tree",
        "excerpt": "A framework-agnostic decision tree for picking the right mobile stack, shaped by 120 engagements and 11M installs.",
        "category": "Mobile",
        "date": "Nov 12, 2025",
        "read_time": "11 min",
        "author": "Ada Okonkwo",
        "cover": "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": False,
        "body": [
            "Every mobile framework claim you'll read in 2026 is partially right and totally useless without context. We'll share the decision tree we actually use — broken down by product stage, team topology, and the five or six places native still wins outright.",
        ],
    },
    {
        "slug": "ragops",
        "title": "RAG-Ops — Running retrieval like a database",
        "excerpt": "The five SLOs we run against every retrieval pipeline we ship. If you can't answer them, you don't have production RAG — you have a demo.",
        "category": "AI",
        "date": "Oct 30, 2025",
        "read_time": "12 min",
        "author": "Samir Bose",
        "cover": "https://images.unsplash.com/photo-1527474305487-b87b222841cc?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": False,
        "body": [
            "RAG is the new CRUD. And like CRUD, the difference between a demo and production is mostly about the things no one wants to build — observability, schema migrations, and a team on-call.",
        ],
    },
    {
        "slug": "design-systems-physics",
        "title": "Design Systems That Obey Physics",
        "excerpt": "Momentum, friction, and mass are not metaphors in a design system. They're the only way interfaces feel alive.",
        "category": "Design",
        "date": "Oct 14, 2025",
        "read_time": "8 min",
        "author": "Lea Vermont",
        "cover": "https://images.unsplash.com/photo-1558655146-9f40138edfeb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": False,
        "body": [
            "Every interface that has ever felt alive obeys a physical model somewhere underneath. Motion without mass is a cartoon; mass without friction is chaos. Here's the physics we bake into every Reachvel design system.",
        ],
    },
    {
        "slug": "edge-native-ecommerce",
        "title": "Edge-Native Commerce — The 900ms Ceiling",
        "excerpt": "Why we won't ship a luxury storefront with an LCP above 1.1s — and how we hit it even with live personalization.",
        "category": "Web",
        "date": "Sep 28, 2025",
        "read_time": "6 min",
        "author": "Kenji Park",
        "cover": "https://images.unsplash.com/photo-1483985988355-763728e1935b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": False,
        "body": [
            "A luxury storefront that takes 2.3 seconds to render has already lost. We'll walk through the edge architecture we use to hit 900ms LCP — even with live personalization, live inventory, and live recommendations.",
        ],
    },
]


ROLES_SEED = [
    {"title": "Senior Staff Engineer, AI Platform", "dept": "Engineering", "location": "San Francisco · Remote", "type": "Full-time",
     "description": "Own our AI platform end-to-end: retrieval, evals, observability, and production guardrails. 8+ years experience building at scale."},
    {"title": "Lead Product Designer", "dept": "Design", "location": "Toronto · Remote", "type": "Full-time",
     "description": "Lead client-facing design engagements across web, mobile, and brand. Portfolio that shows craft, not templates."},
    {"title": "iOS Engineer", "dept": "Mobile", "location": "Remote (Americas)", "type": "Full-time",
     "description": "Ship native Swift/SwiftUI apps that millions of people love. Deep knowledge of performance, accessibility, and app store strategy."},
    {"title": "Data Engineer, Warehousing", "dept": "Data", "location": "Bengaluru · Hybrid", "type": "Full-time",
     "description": "Design and build analytics warehouses that power billion-row queries. Snowflake/dbt/Airflow experience required."},
    {"title": "ML Engineer, RAG Systems", "dept": "AI", "location": "Remote (EU / Americas)", "type": "Full-time",
     "description": "Ship production retrieval systems — chunking, embeddings, rerankers, and evals. LangGraph or equivalent experience valued."},
    {"title": "Creative Director", "dept": "Brand", "location": "Toronto", "type": "Full-time",
     "description": "Lead the brand and motion practice. Direct identity systems, visual language, and the studio's own aesthetic."},
    {"title": "Technical Program Manager", "dept": "Delivery", "location": "San Francisco · Hybrid", "type": "Full-time",
     "description": "Partner with engineering leads to keep cross-discipline engagements shipping on time. Systems thinker, not a task-pusher."},
    {"title": "Engineering Intern — Summer 2026", "dept": "Engineering", "location": "Bengaluru", "type": "Internship",
     "description": "Spend a summer with our platform team. Open to final-year CS / SWE students with strong systems fundamentals."},
]
